"""
Deterministic closed-loop runner for operator optimization agents.

This module is the coordinator that OpenCode agents should call instead of
having long multi-agent chats decide everything.  The LLM part is intentionally
small: produce one ChangeProposal.  The deterministic runner owns patching,
compilation, correctness, benchmark, A/B decision, version promotion and logs.
"""
from __future__ import annotations

import json
import re
import time
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Iterable, Sequence

from agent_system.domain_memory import DomainMemory
from agent_system.global_best import (
    BaselineSource,
    publish_global_best,
    resolve_baseline_source,
)
from agent_system.kernel_version_store import KernelVersionStore
from agent_system.optimization_log import OptimizationEntry, OptimizationLog
from agent_system.operator_registry import get_operator
from agent_system.paths import (
    PROJECT_ROOT,
    list_run_dirs,
    new_run_dir,
    update_results_summary,
    write_latest_run,
)
from agent_system.roofline_engine import KernelConfig, analyze, suggest_split_k
from agent_system.strategy_schema import (
    ChangeProposal,
    OptimizationPhase,
    PatchApplyError,
    apply_change_proposal,
    validate_single_change,
)


DEFAULT_OPERATOR_ID = "flashattention_kvcache_decode"
DEFAULT_KERNEL = PROJECT_ROOT / "kernel" / "splitk_h128.cu"


@dataclass
class ClosedLoopResult:
    run_id: str
    run_dir: str
    mode: str
    status: str
    rounds: int
    keep: int
    reject: int
    error: int
    nochange: int
    logs_dir: str
    summary_path: str
    baseline_source: str = ""
    baseline_path: str = ""
    global_best_path: str = ""

    def to_dict(self) -> dict:
        return asdict(self)


def _json_default(value):
    if isinstance(value, Path):
        return str(value)
    return value


def _write_json(path: Path, data: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, ensure_ascii=False, indent=2, default=_json_default), encoding="utf-8")


def _append_event(run_dir: Path, event: str, **payload) -> None:
    record = {
        "timestamp": time.strftime("%Y-%m-%d %H:%M:%S"),
        "event": event,
        **payload,
    }
    with open(run_dir / "events.jsonl", "a", encoding="utf-8") as f:
        f.write(json.dumps(record, ensure_ascii=False, default=_json_default) + "\n")


def _target_config(cfg: KernelConfig) -> str:
    return (
        f"batch={cfg.batch_size},seq={cfg.seqlen_kv},"
        f"d={cfg.headdim},heads={cfg.num_heads},heads_k={cfg.num_heads_k}"
    )


def _safe_name(value: str, default: str = "candidate") -> str:
    safe = "".join(c if c.isalnum() or c in "-_" else "_" for c in value)
    return (safe or default)[:80]


def load_proposals(path: str | Path | None) -> list[ChangeProposal]:
    if not path:
        return []
    data = json.loads(Path(path).read_text(encoding="utf-8-sig"))
    if isinstance(data, dict) and "proposals" in data:
        data = data["proposals"]
    elif isinstance(data, dict) and "proposal" in data:
        data = data["proposal"]
    if isinstance(data, dict):
        data = [data]
    if not isinstance(data, list):
        raise ValueError("proposal JSON must be an object, list, or {'proposals': [...]}")
    return [ChangeProposal(**item) for item in data]


def default_proposal(
    round_idx: int,
    source: str,
    phase: OptimizationPhase = "tune",
) -> ChangeProposal | None:
    """Return a bounded local proposal for smoke/dry-run demos.

    Real OpenCode usage should normally pass a proposal JSON generated by Coder.
    The default keeps the system runnable on a clean checkout.
    """
    match = re.search(r"static constexpr int NUM_SPLITS = (\d+);", source)
    if not match:
        return None
    current = int(match.group(1))
    candidates = [8, 12, 16, 4, 24]
    next_value = next((v for v in candidates[round_idx:] + candidates[:round_idx] if v != current), current)
    before = match.group(0)
    after = f"static constexpr int NUM_SPLITS = {next_value};"
    scale = "micro"
    change_type = "param_tune"
    max_changed_lines = 6
    summary = f"tune NUM_SPLITS from {current} to {next_value}"
    if phase == "explore":
        scale = "macro"
        change_type = "loop_transform"
        max_changed_lines = 40
        summary = f"explore Split-K structure by changing NUM_SPLITS {current}->{next_value}"
    elif phase == "stabilize":
        scale = "meso"
        change_type = "loop_transform"
        max_changed_lines = 40
        summary = f"stabilize Split-K fanout {current}->{next_value}"

    return ChangeProposal(
        proposal_id=f"auto_num_splits_{current}_to_{next_value}_r{round_idx + 1}",
        target="NUM_SPLITS",
        change_type=change_type,
        one_line_summary=summary,
        before=before,
        after=after,
        hypothesis="adjust Split-K parallelism for decode occupancy",
        risk="low",
        max_changed_lines=max_changed_lines,
        scale=scale,
        phase=phase,
        rollback_plan="discard candidate unless compile/correctness/A-B pass",
    )


def _select_proposal(
    round_idx: int,
    current_code: str,
    explicit: Sequence[ChangeProposal],
    phase: OptimizationPhase,
    allow_auto_proposal: bool,
) -> ChangeProposal | None:
    if round_idx < len(explicit):
        return explicit[round_idx]
    if not allow_auto_proposal:
        return None
    return default_proposal(round_idx, current_code, phase=phase)


def _record_log(
    log: OptimizationLog,
    iteration: int,
    cfg: KernelConfig,
    baseline_version: str,
    verdict: str,
    category: str,
    reason: str,
    proposal: ChangeProposal | None = None,
    candidate_ms: float | None = None,
    speedup: float | None = None,
    correctness: bool | None = None,
) -> None:
    ts = time.strftime("%Y-%m-%d %H:%M:%S")
    log.record(OptimizationEntry(
        iteration=iteration,
        timestamp=ts,
        change_description=proposal.one_line_summary if proposal else "no proposal",
        target_config=_target_config(cfg),
        baseline_time_ms=0.0,
        candidate_time_ms=candidate_ms,
        speedup=speedup,
        bandwidth_util_before=0.0,
        bandwidth_util_after=None,
        correctness_passed=correctness,
        verdict=verdict,
        gap_to_roofline=None,
        category=category,
        proposal_target=proposal.target if proposal else "",
        diff_summary=proposal.to_diff_summary() if proposal else "",
        baseline_version=baseline_version,
        promoted_version="",
        noise_margin=0.0,
        reject_reason=reason,
        used_median=False,
    ))


def _run_dry_loop(
    cfg: KernelConfig,
    initial_code: str,
    operator_id: str,
    proposals: Sequence[ChangeProposal],
    log: OptimizationLog,
    store: KernelVersionStore,
    memory: DomainMemory,
    run_dir: Path,
    max_rounds: int,
    phase: OptimizationPhase,
    allow_auto_proposal: bool,
    proposal_required: bool,
) -> list[dict]:
    v0 = store.add_source(operator_id, initial_code, "initial baseline", verdict="KEEP", metrics={})
    store.promote(v0.version_id)
    current_code = initial_code
    current_version = v0.version_id
    decisions: list[dict] = []

    for idx in range(max_rounds):
        iteration = idx + 1
        round_dir = run_dir / "rounds" / f"round_{iteration:03d}"
        round_dir.mkdir(parents=True, exist_ok=True)
        (round_dir / "baseline_a.cu").write_text(current_code, encoding="utf-8")

        roof = analyze(cfg)
        bottleneck = (
            f"{roof.bound_type}; suggested_split_k={suggest_split_k(cfg)}; "
            f"batch_heads={cfg.batch_size * cfg.num_heads}"
        )
        _write_json(round_dir / "analysis.json", {
            "iteration": iteration,
            "mode": "dry-run",
            "baseline_version": current_version,
            "config": asdict(cfg),
            "roofline": asdict(roof),
            "bottleneck": bottleneck,
        })

        proposal = _select_proposal(idx, current_code, proposals, phase, allow_auto_proposal)
        if proposal is None:
            reason = (
                "Coder proposal is required, but no proposal artifact was provided"
                if proposal_required else
                "no proposal generated"
            )
            verdict = "ERROR" if proposal_required else "NOCHANGE"
            category = "error_agent_output" if proposal_required else "nochange"
            decision = {
                "iteration": iteration,
                "verdict": verdict,
                "category": category,
                "reason": reason,
                "baseline_version": current_version,
            }
            _record_log(log, iteration, cfg, current_version, verdict, category, reason, correctness=False)
            _write_json(round_dir / "decision.json", decision)
            _append_event(run_dir, "round.agent_output_error" if proposal_required else "round.nochange", **decision)
            decisions.append(decision)
            continue

        _write_json(round_dir / "proposal.json", proposal.to_dict())
        ok, reason = validate_single_change(proposal)
        if not ok:
            decision = {
                "iteration": iteration,
                "verdict": "NOCHANGE",
                "category": "nochange",
                "reason": reason,
                "proposal_id": proposal.proposal_id,
                "baseline_version": current_version,
            }
            _record_log(log, iteration, cfg, current_version, "NOCHANGE", "nochange", reason, proposal)
            _write_json(round_dir / "decision.json", decision)
            _append_event(run_dir, "round.invalid_proposal", **decision)
            decisions.append(decision)
            continue

        try:
            candidate_code = apply_change_proposal(current_code, proposal)
        except PatchApplyError as exc:
            reason = str(exc)
            memory.record_failure(
                category="patch_error",
                symptom=reason,
                root_cause="ChangeProposal.before did not uniquely match current source",
                fix="emit exact before/after snippets or provide patched_source",
                config=_target_config(cfg),
            )
            decision = {
                "iteration": iteration,
                "verdict": "ERROR",
                "category": "error_patch",
                "reason": reason,
                "proposal_id": proposal.proposal_id,
                "baseline_version": current_version,
            }
            _record_log(log, iteration, cfg, current_version, "ERROR", "error_patch", reason, proposal, correctness=False)
            _write_json(round_dir / "decision.json", decision)
            _append_event(run_dir, "round.patch_error", **decision)
            decisions.append(decision)
            continue

        cand_name = _safe_name(proposal.proposal_id)
        (round_dir / f"cand_{cand_name}.cu").write_text(candidate_code, encoding="utf-8")
        reason = "dry-run skipped compile/correctness/benchmark; rerun with --real on a MACA GPU"
        decision = {
            "iteration": iteration,
            "verdict": "SKIP",
            "category": "nochange",
            "reason": reason,
            "proposal_id": proposal.proposal_id,
            "proposal_target": proposal.target,
            "baseline_version": current_version,
            "candidate_source": f"cand_{cand_name}.cu",
            "patch_applied": True,
        }
        _record_log(log, iteration, cfg, current_version, "SKIP", "nochange", reason, proposal, correctness=None)
        _write_json(round_dir / "decision.json", decision)
        _append_event(run_dir, "round.dry_skip", **decision)
        decisions.append(decision)

    return decisions


def _run_real_loop(
    cfg: KernelConfig,
    initial_code: str,
    operator_id: str,
    proposals: Sequence[ChangeProposal],
    log: OptimizationLog,
    store: KernelVersionStore,
    memory: DomainMemory,
    run_dir: Path,
    max_rounds: int,
    phase: OptimizationPhase,
    noise_margin: float,
    warmup: int,
    repeats: int,
    allow_auto_proposal: bool,
) -> list[dict]:
    from agent_system.real_orchestrator import run_ab_loop

    v0 = store.add_source(operator_id, initial_code, "initial baseline", verdict="KEEP", metrics={})
    store.promote(v0.version_id)
    state = {"idx": 0}

    def gen(_cfg, _bottleneck, _memory, current_code):
        idx = state["idx"]
        state["idx"] += 1
        return _select_proposal(idx, current_code, proposals, phase, allow_auto_proposal)

    results = run_ab_loop(
        cfg=cfg,
        initial_code=initial_code,
        initial_version_id=v0.version_id,
        generate_proposal_fn=gen,
        memory=memory,
        log=log,
        version_store=store,
        workdir=run_dir / "rounds",
        max_iterations=max_rounds,
        noise_margin=noise_margin,
        warmup=warmup,
        repeats=repeats,
    )
    decisions = []
    for result in results:
        decisions.append({
            "iteration": result.iteration,
            "verdict": result.verdict,
            "baseline_version": result.baseline_version,
            "promoted_version": result.promoted_version,
            "baseline_time_ms": result.baseline_time_ms,
            "candidate_time_ms": result.candidate_time_ms,
            "speedup": result.speedup,
            "correctness_passed": result.correctness_passed,
            "reject_reason": result.reject_reason,
            "proposal_id": result.proposal.proposal_id if result.proposal else "",
        })
    return decisions


def _publish_latest_keep(
    *,
    operator_id: str,
    decisions: Sequence[dict],
    store: KernelVersionStore,
    run_dir: Path,
) -> dict | None:
    kept = [
        d for d in decisions
        if d.get("verdict") == "KEEP" and d.get("promoted_version")
    ]
    if not kept:
        return None
    decision = kept[-1]
    version = store.get(decision["promoted_version"])
    source_path = store.base_dir / version.file
    source_code = source_path.read_text(encoding="utf-8")
    return publish_global_best(
        operator_id=operator_id,
        source_code=source_code,
        run_id=run_dir.name,
        run_dir=run_dir,
        version_id=version.version_id,
        metrics={**version.metrics, "decision": decision},
        description=version.description,
    )


def run_closed_loop(
    operator_id: str = DEFAULT_OPERATOR_ID,
    kernel_path: str | Path = DEFAULT_KERNEL,
    rounds: int = 1,
    dry_run: bool = True,
    proposal_path: str | Path | None = None,
    phase: OptimizationPhase = "tune",
    tag: str = "closed_loop",
    batch: int = 1,
    seq_kv: int = 4096,
    headdim: int = 128,
    num_heads: int = 8,
    num_heads_k: int = 8,
    noise_margin: float = 0.03,
    warmup: int = 5,
    repeats: int = 30,
    baseline_source: BaselineSource = "auto",
    proposal_required: bool = False,
    allow_auto_proposal: bool = True,
) -> ClosedLoopResult:
    spec = get_operator(operator_id)
    requested_kernel = Path(kernel_path)
    resolved_requested_kernel = requested_kernel if requested_kernel.is_absolute() else PROJECT_ROOT / requested_kernel
    if operator_id != DEFAULT_OPERATOR_ID and resolved_requested_kernel == DEFAULT_KERNEL:
        starter = spec.metadata.get("starter_cuda_maca")
        if starter:
            kernel_path = (PROJECT_ROOT / starter).resolve()

    initial_code, resolved_baseline_path, baseline_meta = resolve_baseline_source(
        operator_id=operator_id,
        kernel_path=kernel_path,
        baseline_source=baseline_source,
    )

    run_dir = new_run_dir(tag, operator_id=operator_id)
    logs_dir = run_dir / "logs"
    cfg = KernelConfig(
        batch_size=batch,
        seqlen_kv=seq_kv,
        headdim=headdim,
        num_heads=num_heads,
        num_heads_k=num_heads_k,
    )
    proposals: list[ChangeProposal] = []
    mode = "dry-run" if dry_run else "real"
    global_best_entry = baseline_meta.get("global_best") or {}
    global_best_path = str(global_best_entry.get("source_path", ""))

    manifest = {
        "run_id": run_dir.name,
        "mode": mode,
        "status": "running",
        "created_at": time.strftime("%Y-%m-%d %H:%M:%S"),
        "operator_id": operator_id,
        "kernel_path": str(kernel_path),
        "baseline_source": baseline_source,
        "baseline_kind": baseline_meta.get("kind"),
        "baseline_resolved_path": str(resolved_baseline_path),
        "global_best_path": global_best_path,
        "proposal_required": proposal_required,
        "allow_auto_proposal": allow_auto_proposal,
        "rounds_requested": rounds,
        "phase": phase,
        "config": asdict(cfg),
        "proposal_path": str(proposal_path) if proposal_path else "",
        "artifact_contract": {
            "events": "events.jsonl",
            "logs": "logs/",
            "versions": "versions/",
            "rounds": "rounds/round_###/",
        },
    }
    _write_json(run_dir / "run_manifest.json", manifest)
    write_latest_run(run_dir, operator_id=operator_id)
    _append_event(
        run_dir,
        "run.start",
        mode=mode,
        operator_id=operator_id,
        kernel_path=str(kernel_path),
        baseline_source=baseline_source,
        baseline_resolved_path=str(resolved_baseline_path),
    )

    memory = DomainMemory(base_dir=run_dir / "memory")
    log = OptimizationLog(log_dir=logs_dir)
    store = KernelVersionStore(run_dir / "versions")

    try:
        if (
            not dry_run
            and operator_id != DEFAULT_OPERATOR_ID
            and spec.metadata.get("requires_operator_specific_evaluator")
        ):
            raise RuntimeError(
                f"real closed_loop for {operator_id} requires an operator-specific "
                "compile/correctness/benchmark evaluator; use the task benchmark "
                "scripts or connect a MoE evaluator before real A/B"
            )
        proposals = load_proposals(proposal_path)
        if dry_run:
            decisions = _run_dry_loop(
                cfg, initial_code, operator_id, proposals, log, store, memory,
                run_dir, rounds, phase, allow_auto_proposal, proposal_required
            )
        else:
            if proposal_required and not allow_auto_proposal and len(proposals) < rounds:
                raise RuntimeError(
                    "Coder proposal artifact is required for every requested round; "
                    f"got {len(proposals)} proposal(s) for {rounds} round(s)"
                )
            decisions = _run_real_loop(
                cfg, initial_code, operator_id, proposals, log, store, memory,
                run_dir, rounds, phase, noise_margin, warmup, repeats, allow_auto_proposal
            )
        status = "completed"
    except Exception as exc:
        status = "failed"
        reason = str(exc)
        category = (
            "error_agent_output"
            if "Coder proposal artifact" in reason or "proposal" in reason.lower()
            else "error_runtime"
        )
        decisions = [{
            "iteration": len(log.entries) + 1,
            "verdict": "ERROR",
            "category": category,
            "reason": reason,
        }]
        _record_log(
            log=log,
            iteration=decisions[0]["iteration"],
            cfg=cfg,
            baseline_version=store.current_best.get(operator_id, ""),
            verdict="ERROR",
            category=category,
            reason=reason,
            correctness=False,
        )
        manifest["error"] = reason
        _append_event(run_dir, "run.error", error=reason)
    finally:
        # Always refresh latest_run so failed runs remain inspectable.
        write_latest_run(run_dir, operator_id=operator_id)

    counts = {
        "keep": sum(1 for d in decisions if d.get("verdict") == "KEEP"),
        "reject": sum(1 for d in decisions if d.get("verdict") == "REJECT"),
        "error": sum(1 for d in decisions if d.get("verdict") == "ERROR"),
        "nochange": sum(1 for d in decisions if d.get("verdict") in {"NOCHANGE", "SKIP"}),
    }
    if any(d.get("category") == "error_agent_output" for d in decisions):
        status = "failed"
    published_best = _publish_latest_keep(
        operator_id=operator_id,
        decisions=decisions,
        store=store,
        run_dir=run_dir,
    )
    if published_best:
        manifest["published_global_best"] = published_best
        _append_event(run_dir, "global_best.publish", **published_best)

    manifest["status"] = status
    manifest["completed_at"] = time.strftime("%Y-%m-%d %H:%M:%S")
    manifest["rounds_completed"] = len(decisions)
    manifest["counts"] = counts
    _write_json(run_dir / "run_manifest.json", manifest)
    _append_event(run_dir, "run.complete", status=status, **counts)

    summary_path = logs_dir / "summary.md"
    update_results_summary([
        "# Latest Closed Loop Run",
        "",
        f"- operator_id: `{operator_id}`",
        f"- run_id: `{run_dir.name}`",
        f"- mode: `{mode}`",
        f"- status: `{status}`",
        f"- baseline_source: `{baseline_source}`",
        f"- baseline_path: `{resolved_baseline_path}`",
        f"- global_best_path: `{published_best.get('source_path') if published_best else global_best_path}`",
        f"- rounds: `{len(decisions)}`",
        f"- keep/reject/error/nochange: `{counts['keep']}/{counts['reject']}/{counts['error']}/{counts['nochange']}`",
        f"- run_dir: `{run_dir}`",
        f"- logs: `{logs_dir}`",
        "",
        "Recent runs:",
        *[f"- `{p.name}`" for p in list_run_dirs(limit=5, operator_id=operator_id)],
    ], operator_id=operator_id)

    return ClosedLoopResult(
        run_id=run_dir.name,
        run_dir=str(run_dir),
        mode=mode,
        status=status,
        rounds=len(decisions),
        keep=counts["keep"],
        reject=counts["reject"],
        error=counts["error"],
        nochange=counts["nochange"],
        logs_dir=str(logs_dir),
        summary_path=str(summary_path),
        baseline_source=baseline_source,
        baseline_path=str(resolved_baseline_path),
        global_best_path=published_best.get("source_path", global_best_path) if published_best else global_best_path,
    )


def result_to_json(result: ClosedLoopResult) -> str:
    return json.dumps(result.to_dict(), ensure_ascii=False, indent=2)
